require 'rubygems' if RUBY_VERSION < '1.9'
require 'rake'
require 'rake/cpp'

Rake::Cpp.new do |cpp|
  cpp.target               = 'zlib'
  cpp.programming_language = 'c'
  cpp.source_search_paths  = [ 'src' ]
  cpp.header_search_paths  = [ 'include' ]
  cpp.objects_path         = '.'
  cpp.library_dependencies << 'z'
  cpp.generated_files      << 'rake.gz'
end
