=begin

= A Minimal Example for Rake-Builder

=end

require 'rubygems' if RUBY_VERSION < '1.9'
require 'rake'
require 'rake/builder'

Rake::Builder.new do |builder|
  builder.target = 'hello_world_cpp'
end
