require 'rubygems' if RUBY_VERSION < '1.9'
require 'rake'
require 'rake/builder'

Rake::Builder.new do |builder|
  builder.target               = 'search-paths'
  builder.source_search_paths  = [ 'src' ]
  builder.objects_path         = '.'
end

