require 'rubygems' if RUBY_VERSION < '1.9'
require 'rake'
require 'rake/builder'

Rake::Builder.new do |builder|
  builder.target               = 'unit'
  builder.source_search_paths  = [ 'src' ]
  builder.header_search_paths  = [ 'include' ]
end

Rake::Builder.new do |builder|
  builder.task_namespace       = 'test'
  builder.target               = 'test_unit'
  builder.source_search_paths  = [ 'test', 'src/units.*' ]
  builder.header_search_paths  = [ 'include' ]
  builder.objects_path         = 'test'
  builder.compilation_options  = '-DDEBUG'
end

